apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: sso-egress
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: sso
  policyTypes: ["Egress"]
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
    - ports:
        - protocol: TCP
          port: 443
        - protocol: TCP
          port: 587
        - protocol: TCP
          port: 465
    - to:
        - podSelector:
            matchLabels:
              postgres-operator.crunchydata.com/cluster: sso-postgres
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: sso-redis-ha
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: new-api
          podSelector:
            matchLabels:
              app.kubernetes.io/name: cap
      ports:
        - protocol: TCP
          port: 5432
        - protocol: TCP
          port: 6379
        - protocol: TCP
          port: 3000
