resolver 10.96.0.10 valid=10s ipv6=off;
resolver_timeout 2s;
set $sso_upstream sso.sso.svc.cluster.local;

proxy_pass http://$sso_upstream:80;
proxy_http_version 1.1;
proxy_set_header Host user.xem8k5.top;
proxy_set_header X-Original-Host $host;
proxy_set_header X-Forwarded-Host user.xem8k5.top;
proxy_set_header X-Forwarded-Proto https;
proxy_set_header X-Forwarded-Port 443;
proxy_set_header X-Real-IP $remote_addr;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

proxy_connect_timeout 10s;
proxy_send_timeout 120s;
proxy_read_timeout 120s;
proxy_request_buffering off;
proxy_buffering off;
proxy_cache off;
